file_format: "1"
id: eyeslash_corne
name: Eyeslash Sofle
url: https://github.com/juniorz/zmk-corne-dongle
type: shield
requires: [pro_micro]
features:
  - keys
  - display
outputs:
  - usb
  - ble
siblings:
  - eyeslash_corne_central_dongle